jobs:
  include:
  - language: ruby

    addons:
      postgresql: 9.6
    services:
      - redis-server

    cache:
      bundler: true

    before_script:
    - bundle exec rake db:create db:schema:load RAILS_ENV=test
    - cp spec/fixtures/service_account_cred.json.travis config/secure/service_account_cred.json

    script:
    - bundle exec rspec
    - bundle exec standardrb
    - bundle exec bundle audit check --update
    - bundle exec brakeman -A -q --no-pager --ensure-latest
