name: XML Schema Validation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lesson_schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check valid XML
        run: xmllint --schema public/xmlns/lesson.xsd --noout schema_tests/lesson/valid/*/*.xml
      - name: Check invalid XML
        run: ./schema_tests/invalid.sh public/xmlns/lesson.xsd schema_tests/lesson/invalid/*/*.xml
